steps:
  - name: 'gcr.io/cloud-builders/go'
    id: Executando install
    args:
      - 'install'
      - 'sqrt'
    env: ['GOPATH=/workspace']

  - name: 'gcr.io/cloud-builders'
    id: Executando testes
    args:
      - 'test'
      - 'sqrt'
    env: ['GOPATH=/workspace']

  - name: 'gcr.io/cloud-builders/docker'
    id: Executando docker build
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/go-hpa:$SHORT_SHA'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    id: Executando push image
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/go-hpa:$SHORT_SHA'

  - name: 'gcr.io/cloud-builders/gcloud'
    id: Atualizando deployment
    entrypoint: /bin/sh
    args:
      - '-c'
      - |
        sed "s#APP_IMAGE#gcr.io/$PROJECT_ID/go-hpa:$SHORT_SHA#g" k8s/deployment.yaml > k8s/deployment_final.yaml

  - name: 'gcr.io/cloud-builders/kubectl'
    id: Executando deploy k8s
    args:
      - 'apply'
      - '-f'
      - 'k8s/deployment_final.yaml'