apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-hpa
  labels:
    app: go-hpa
spec:
  selector:
    matchLabels:
      app: go-hpa
  replicas: 1
  template:
    metadata:
      labels:
        app: go-hpa
    spec:
      containers:
        - name: go-hpa
          image: APP_IMAGE
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "50m"
            limits:
              cpu: "100m"