steps:
  - name: 'gcr.io/cloud-builders/go'
    id: Executando install
    args:
      - 'install'
      - 'sqrt'
    env: ['GOPATH=/workspace/go']

  - name: 'gcr.io/cloud-builders/go'
    id: Executando testes
    args:
      - 'test'
      - 'sqrt'
    env: ['GOPATH=/workspace/go']

  - name: 'gcr.io/cloud-builders/docker'
    id: Executando docker build
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/go-hpa:latest'
      - 'go/'

images:
  - 'gcr.io/$PROJECT_ID/go-hpa:latest'